version: '3'

volumes:
  store:
    driver: local
  bundle:
    driver: local

services:
  postgresql:
    image: postgres:9.6.2
    ports:
      - "5432"
  web:
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - postgresql
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=postgresql
    volumes:
      - .:/papinotas
