# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b558bef92d70c55d85b9439c741d6e192acf13794be12b8b04f0d4c811ca432e80f6542dbf2f46553eee18a799f948480f920e7524239c8349aaeb1ab7b5ceb

test:
  secret_key_base: b7b95bacb4744e23a89cdcc314a848ec087987e96dec26fe544a324b01a9220d0616e52838f9bcfdc8659402d0e4abde411ce96a48dcc07e2fed4f5f69360245

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
